### ISSUE TITLE
Add a description to the GitHub project

### ISSUE THREAD

**Issue by njh** [eclipse/paho.mqtt-spy#1]
"No description or website provided."

This could become:

* Description: "JavaFX utility to help monitor activity on MQTT topics"
* URL: https://github.com/eclipse/paho.mqtt-spy/wiki/Home

**Comment by kamilfb** [comment]
Thanks @njh for reporting it. I can't change it myself unfortunately - I will speak to an Eclipse admin to get that sorted...

**Comment by kamilfb** [comment]
Done! Didn't add the URL - was too long! ;-)

**Comment by njh** [comment]
Great!
