### ISSUE TITLE
Unable to connect to rabbitmq broker in another PC

### ISSUE THREAD

**Issue by manoj123448** [eclipse/paho.mqtt-spy#13]
I am using Mqttspy GUI. If I give localhost or 127.0.0.1 I am able to connect to Rabbitmq without any issues. But if I give system IP address or if RabbitMQ is in another PC I am not able to connect through Mqttspy

**Comment by kamilfb** [comment]
https://github.com/kamilfb/mqtt-spy/issues/109#issuecomment-283714868
