### ISSUE TITLE
Can't add publications/subscriptions before connecting

### ISSUE THREAD

**Issue by alieslam** [eclipse/paho.mqtt-spy#14]
Whenever i try to add publications/subscription before connecting, then press "+Add topic",the topic twists to the default "/samplePublication/" or "/sampleSubscription/". 
![image](https://cloud.githubusercontent.com/assets/8179651/23504726/67ac4cfa-ff49-11e6-92c9-6cc83b610707.png)

I have tried both versions 0.5.4 and (beta) 0.6.0, and both have the same problem.

**Comment by alieslam** [comment]
@kamilfb, 
Apologies, I rushed submitting this issue. I also missed the note to press  "Enter" for submitting a new value.

**Comment by kamilfb** [comment]
No worries. Thanks for using it!
