### ISSUE TITLE
Pretty Json display pane only displays 2 lines

### ISSUE THREAD

**Issue by MrBillium** [eclipse/paho.mqtt-spy#16]
Pretty Json is a nice way to see complex JSON but the display pane only shows 2 1/2 rows and will not resize forcing the user to use the scrollbars.

Please  make Pretty Json pane bigger or resizable

**Comment by kamilfb** [comment]
Hi @MrBillium - any chance you could attach a screenshot to explain further?

**Comment by MrBillium** [comment]
Unfortunately ( or fortunately)  no,

 

The problem is not now reproducible but I have since  rebooted my PC  – something I very rarely do so perhaps that fixed it. 

 

I have simulated the look  of the problem by dragging the summary pane divider up but when I had the issue I could not pull it down – it was fixed.

 

 

Bill

**Comment by kamilfb** [comment]
Thanks @MrBillium
