### ISSUE TITLE
Chart problem adding/deleting entry

### ISSUE THREAD

**Issue by swilson86** [eclipse/paho.mqtt-spy#19]
There is a bug on release 56 of 6.0 Beta in the chart functionality. If I add a 2nd (or more) entry to the chart and then remove it, it doesn't get fully removed.

**Comment by kamilfb** [comment]
Thanks for raising this @swilson86. I will investigate and report back.

**Comment by kamilfb** [comment]
@swilson86 could you try latest beta? https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta13
