### ISSUE TITLE
Disconnect (keep tab) -> Reconnect -> no messages

### ISSUE THREAD

**Issue by benjaminaigner** [eclipse/paho.mqtt-spy#20]
Hello,

if you connect with mqtt-spy to a broker and disconnect via right-click on the tab (keep tab),
no messages are received after a reconnect.

It is necessary to close the tab to receive messages again.

Best regards

**Comment by kamilfb** [comment]
@benjaminaigner , after the reconnect, have you re-subscribed to all topics, either manually or in connection settings?

**Comment by benjaminaigner** [comment]
I had to re-subscribe all topics, which is not obvious :-)

Bug or feature ^^?

**Comment by kamilfb** [comment]
Feature - because you manually disconnected, you had to manually resubscribe :)

**Comment by benjaminaigner** [comment]
Sounds practicable :-)
THX for the hint.
