### ISSUE TITLE
stacktraces from scripts lack the script filename => debugging tedious

### ISSUE THREAD

**Issue by guillaume-d** [eclipse/paho.mqtt-spy#24]
Replacing in [ScriptRunner.java](https://github.com/eclipse/paho.mqtt-spy/blob/master/spy-common/src/main/java/pl/baczkowicz/spy/scripts/ScriptRunner.java)
```java
lastReturnValue = script.getScriptEngine().eval(new InputStreamReader(FileUtils.loadFileByName(script.getScriptFile().getAbsolutePath())));
```
with the following should fix that (according to <https://stackoverflow.com/questions/2885120/replace-unknown-source-in-java-rhino-jsr223-with-actual-file-name/24559495#24559495>, _**untested**_):

```java
ScriptContext scriptContext = script.getScriptEngine().getContext();
scriptContext.setAttribute(ScriptEngine.FILENAME, script.getScriptFile().getAbsolutePath(), ScriptContext.ENGINE_SCOPE);
try {
    lastReturnValue = script.getScriptEngine().eval(new InputStreamReader(FileUtils.loadFileByName(script.getScriptFile().getAbsolutePath())));
} finally {
    scriptContext.removeAttribute(ScriptEngine.FILENAME, ScriptContext.ENGINE_SCOPE); 
}
```
(See also <https://docs.oracle.com/javase/8/docs/api/javax/script/ScriptContext.html>).

Also scripts on classpath might need to be special-cased.

----
On a related note maybe ``__FILE__`` and ``__DIR__`` (Reference: <https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions#Nashornextensions-Extensionproperties,functionsinglobalobject>)  would work with these changes.

**Comment by kamilfb** [comment]
I will look into this. Thank you for reporting.

**Comment by kamilfb** [comment]
Now available in https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta18 - thanks again @guillaume-d for this!
