### ISSUE TITLE
Repository needs a LICENSE file

### ISSUE THREAD

**Issue by mmilinkov** [eclipse/paho.mqtt-spy#3]
Please add the Eclipse Public License to the repository.

**Comment by jpwsutton** [comment]
Done: https://github.com/eclipse/paho.mqtt-spy/blob/master/LICENSE

**Comment by jpwsutton** [comment]
After a quick chat with @icraggs, It looks like we also need some additional files to comply with the Eclipse legal requirements, from a look at the other paho repositories, I think we need:

- about.html (Example here: https://github.com/eclipse/paho.mqtt.android/blob/master/about.html)
- edl-v10 (Eclipse Distribution Licence)
- epl-v10 (Eclipse Public Licence)
- notice.html (Example here: https://github.com/eclipse/paho.mqtt.android/blob/master/notice.html)

I found some docs here outlining what we need: https://eclipse.org/legal/guidetolegaldoc.php

**Comment by kamilfb** [comment]
@jpwsutton, many thanks for your recent pull (https://github.com/eclipse/paho.mqtt-spy/pull/9) - do you recon we now have everything we need?

**Comment by jpwsutton** [comment]
@kamilfb No worries, Yes I think that's everything that is required now, I'll close this off.
