### ISSUE TITLE
Export Msgs, wrong format?

### ISSUE THREAD

**Issue by TotallyInformation** [eclipse/paho.mqtt-spy#31]
When I copy an individual msg to the clipboard or export a single msg to the clipboard, the message is in text.

If, however, I export "all browsed messages" to clipboard, the format is in binary:

````
<MqttMessage id="33" timestamp="1501833753500" topic="RFX/Lights/undefined/0x001145/2" qos="0" retained="true" encoded="true">eyJzdGF0dXMiOnsicnNzaSI6M30sInRpbWVzdGFtcCI6IjIwMTctMDgtMDNUMDk6MjE6NDEuODE0WiIsIm1zZ0tleXMiOlsic3RhdHVzIiwidG9waWMiLCJfbXNnaWQiLCJ0aW1lc3RhbXAiXX0=</MqttMessage>
````

That doesn't look right and isn't terribly helpful. Could it be fixed?

**Comment by kamilfb** [comment]
@TotallyInformation - I will look into it. Thanks for raising this.

**Comment by kamilfb** [comment]
Fixed available in https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta5
