### ISSUE TITLE
test cases cannot be loaded from the GUI

### ISSUE THREAD

**Issue by guillaume-d** [eclipse/paho.mqtt-spy#33]
On Windows 10 using mqtt-spy-1.0.0.jar with Java 8 with an empty profile (without any connection defined):
In the "Test cases" window loading test cases from the context menu only throws an exception.
A similar exception is thrown while opening that window.
Also the window never opens the first time, a second click in the "Window" menu entry is needed.

I can provide more details if reproducing the problem proves difficult.
BTW:
- mqtt-spy-0.5.4-jar-with-dependencies.jar also had the same problem
- my test cases run otherwise fine with mqtt-spy-damon-1.0.0.jar.

**Comment by kamilfb** [comment]
hi @guillaume-d - many thanks for reporting this. could you try the latest beta? https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta11

**Comment by guillaume-d** [comment]
This works perfeclty now, thanks!
Alas now I found #42!
