### ISSUE TITLE
Charts - JSONPath error

### ISSUE THREAD

**Issue by sandoeg** [eclipse/paho.mqtt-spy#36]
The following JSON formatted messages is being published on topic = home/environment on test.mosquitto.org.

{
          "humidity": 53.57,
          "pressure": 29.96,
          "temperature": 77.38,
          "timestamp": "Tue Sep 26 10:14:02 2017"
}

I am creating a Chart by selecting the topic from the Received messages summary, selecting Charts, then Show payload values for this topic.
I change Type = Payload to Type = JSONPath
I edit the Value expression = $.temperature

Response:
I get no plotted values. 
I get a "java.lang.ClassCastException:java.lang.Double cannot be cast to [C" error.

### Attachments:
Windows 10:

![java version](https://user-images.githubusercontent.com/31491441/30865851-b7d725ec-a2a5-11e7-8fa8-8243bd05bb93.jpg)

Settings:  (ignore cursor at end of series name)

![settings](https://user-images.githubusercontent.com/31491441/30866379-0afd9cf0-a2a7-11e7-9dc2-313c7c3d5a5c.jpg)

Error:

![error](https://user-images.githubusercontent.com/31491441/30865852-b7e7cac8-a2a5-11e7-854f-ba0f0d812709.jpg)

**Comment by gwh-cpnet** [comment]
same for me

**Comment by kamilfb** [comment]
@sandoeg @gwh-cpnet, could you try https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta9 ?

**Comment by sandoeg** [comment]
mqtt-spy 1.0.1-beta9 fixes the problem that I reported.  Thank you for the fix.

**Comment by kamilfb** [comment]
Awesome. Thanks for the feedback!

**Comment by sandoeg** [comment]
Thank you for providing such a great software application.
