### ISSUE TITLE
Amazon AWS connection

### ISSUE THREAD

**Issue by kjordan-sa** [eclipse/paho.mqtt-spy#4]
I am unable to get any type of connection established to an AWS broker. 

I have tried various security configurations.

Any help would be great.

**Comment by kjordan-sa** [comment]
got it working after much trying.

**Comment by kjordan-sa** [comment]
Using AWS I found that the Security setting required are only in the TLS section.

Using the CA cert & client cert mode. TLSv1.2 protocol.
  -  required are the CA Cert, the Client Cert, and the Client Private Key (selected PEM format).

**Comment by kamilfb** [comment]
thank you for sharing the solution!

**Comment by MihirGangoly** [comment]
Dear Kurt,

Having similar issues trying to hook up mqtt-spy to the AWS broker. Issue seems to be with the certificates. Could be of help please?

**Comment by Niondir** [comment]
Any hints on how to setup AMazon ActiveMQ an connect with MQTT Spy? I'm facing same issues.
