### ISSUE TITLE
ClientID longer than 23 characters

### ISSUE THREAD

**Issue by jwosnick** [eclipse/paho.mqtt-spy#44]
MQTT-spy currently doesn't seem to allow the user to specify Client IDs longer than 23 characters. I recognize this is the MQTT standard, but at least one cloud IOT provider seems to require specific Client IDs that are around 35-40 characters long.

Any way to have MQTT-spy allow longer Client IDs?

**Comment by kamilfb** [comment]
@jwosnick have you changed the protocol version to 3.1.1?

**Comment by jwosnick** [comment]
I forced it to 3.1.1 and now it seems to be okay. I do note that the "auto-resolve" protocol option limits to 23 characters. Not what I would have expected but it's working now.

**Comment by kamilfb** [comment]
Cool. Thanks for confirming.
