### ISSUE TITLE
Can not start UI

### ISSUE THREAD

**Issue by theScrabi** [eclipse/paho.mqtt-spy#46]
I tried to start mqtt-spy 1.0 running `java -jar mqtt-spy-1.0.0.jar` however it did not work:
```
Error: Mainclass pl.baczkowicz.mqttspy.Main could not be found or loaded
```

Am I missing something?

**Comment by guillaume-d** [comment]
Does https://github.com/eclipse/paho.mqtt-spy/wiki/FAQs#error-could-not-find-or-load-main-class-plbaczkowiczmqttspymain help?
To help you more one would at least know which OS you are using.

**Comment by theScrabi** [comment]
Ah right, that was the error. Thanks :)

**Comment by riker65** [comment]
> Does https://github.com/eclipse/paho.mqtt-spy/wiki/FAQs#error-could-not-find-or-load-main-class-plbaczkowiczmqttspymain (see #6) help?


on ubuntu 20. java 8 does not have installation candidate.....
so not solved
