### ISSUE TITLE
Can we run different publishing scripts simultaneously ?

### ISSUE THREAD

**Issue by Biswajeeban** [eclipse/paho.mqtt-spy#47]
I've just got a question. Is there any way we can run multiple simulation scripts on mqtt-spy concurrently? Suppose, I write 5 Scripts to publish some values to 5 different topics; instead of starting them one by one, is there any way I can start (run) all the scripts at the same time?

Thanks in advance.
Regards,
Biswa

**Comment by Biswajeeban** [comment]
Hi Kamil, 
is the first one ( one script that publishes to all 5 topics) achievable using JavaScript ? Can I have a simple example of it?

**Comment by kamilfb** [comment]
See the script below - it will publish a message each to the sample1-10 topics
```
function publish()
{
	for (i = 0; i < 10; i++)
	{
		mqttspy.publish("/mqtt-spy/script/sample" + i, "hello" + i);
	}

	// This means all OK, script has completed without any issues and as expected
	return true;
}

publish();
```
