### ISSUE TITLE
LWT Encoding issue in data field

### ISSUE THREAD

**Issue by HeikoScholtes** [eclipse/paho.mqtt-spy#49]
Using MQTT Spy version 1.0.0 build 3 on macOS high sierra + java version "1.8.0_152"
- select LWT checkbox
- select PLAIN in the dropdown
- check retain = true
- enter target topic name
- specify in the Data field the corresponding message payload "OFFLINE"

Result:
In the target topic the encoding is incorrect:
"OFFLINE" results in "8QK ?"

**Comment by kamilfb** [comment]
This is now available in https://github.com/eclipse/paho.mqtt-spy/releases/tag/1.0.1-beta18. Thank you for reporting this @HeikoScholtes .
