### ISSUE TITLE
Raspbian Jessie Pixel Problem

### ISSUE THREAD

**Issue by acestu** [eclipse/paho.mqtt-spy#5]
Hi,
I downloaded the Beta to my windows 10 machine and followed your Youtube tutorial no problem, however when I download the Beta to my raspberry pi 3 running the latest raspbian Jessie Pixel, I check the Java version which is: Java(TM) SE Runtime Environment (build 1.8.0_65-b17) , now the icon in the download folder for the mqtt-spy app is for an archive file and when you double click on it the Xarchiver app opens, does it need to be associated with something else ?

Thanks
Stuart

**Comment by kamilfb** [comment]
Hi. Looks like a problem with file associations in Raspbian. Have you tried starting it from the command line?

**Comment by acestu** [comment]
Hi,
No, I haven't tried from a terminal, what should I type to start it ?

Thanks
Stuart

**Comment by kamilfb** [comment]
Take a look at the Getting Started wiki page. For example:

java -jar mqtt-spy-0.3.0-jar-with-dependencies.jar

(just replace with the correct file name)

**Comment by acestu** [comment]
Hi,
Yes I have tried the obvious but I get this Error:

Error: Could not find or load main class pl.baczkowicz.mqttspy.Main

Thanks
Stuart

**Comment by acestu** [comment]
Hi,

I guess this is a Java issue as I have it installed as you can see from the screenshot, and the error that I am getting is the same one on your Wiki that it says you get if Java above ver 60 is not installed.

Thanks
Stuart
![2016-10-13-201626_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4260227/19365468/74fa1840-9182-11e6-95a1-a42401008d79.png)

**Comment by kamilfb** [comment]
Hi @acestu,

I think you are right - Java on RPi is missing JavaFX support by default.

Found something on SO: http://stackoverflow.com/questions/36961054/can-javafx-be-used-on-raspberry-pi

Looks like downloading the Gluon SDK and copying the jfxrt.jar to your JRE/JDK lib directory might be the solution -  would you like to give it a try?

Also, there might be a way with using OpenJDK - take a look at https://github.com/kamilfb/mqtt-spy/issues/88

Let me know how you get on...

**Comment by acestu** [comment]
Hi,

I downloaded the kit from Gluon and placed the jfxrt.jar file in the java directory but I still get the same error, I will have another look tomorrow, maybe it needs a Path listing somewhere, I will look into Openjdk also

Thanks
Stuart

**Comment by acestu** [comment]
Hi kamilfb,

You may find this page interesting, I didn't have any luck with it myself but then I am a Linux newcomer and maybe somebody with more experience could make it work:

http://chriswhocodes.com/

Thanks
Stuart

**Comment by acestu** [comment]
There seem to be a few methods for getting javafx on the pi,  however, I suspect that it is not working because it is a case of properly declaring the Class Path and Java Path for the raspberry pi.

Thanks
Stuart

**Comment by swilson86** [comment]
Hi. I am unable to install MQTT-Spy for lack of documentation or vague directions like "double click on the jar." Some basic clues should be included in the Getting Started section. I cannot find the file mqtt-spy-0.3.0-jar-with-dependencies.jar after downloading and unzipping the github mqtt-spy software on both Windows 10 and Raspberry Pi. Very frustrating.

**Comment by kamilfb** [comment]
@swilson86 
- you can't "install" mqtt-spy; one can download it and run it
- obviously version 0.3.0 is not in the Downloads section because it's been replaced by newer versions, e.g. 0.5.4; I suggest you try this one
- I'm not sure what you mean by unzipping the github mqtt-spy software; this is not mentioned anywhere in here; mqtt-spy ships as a runnable jar file

**Comment by swilson86** [comment]
Thanks Kamilfb. On this page you mention the 0.3.0 jar file: https://github.com/eclipse/paho.mqtt-spy/wiki/GettingStarted  I downloaded all the zipped files from https://github.com/eclipse/paho.mqtt-spy and nowhere do I see any version of a jar file not 0.3.0 or 0.5.4  Obviously there is some critical piece of information missing on your GettingStarted page.

**Comment by swilson86** [comment]
Found the jar file at https://github.com/eclipse/paho.mqtt-spy/wiki/Downloads  May I suggest in the documentation under Getting Started you place this link or an explanation. I totally missed the downloads link as it was the last thing in the list and logically should be the first thing in the list. Thanks!

**Comment by kamilfb** [comment]
Getting Started updated - thanks @swilson86.
