### ISSUE TITLE
Doesn't work with Java v10

### ISSUE THREAD

**Issue by TotallyInformation** [eclipse/paho.mqtt-spy#66]
On Windows 10 64bit, MQTT-Spy doesn't work with the current version of Java (v10).

Are there plans to fix this?

For reference, Java v8 is end of life in January 2019 for enterprise users.

**Comment by hexenmeister** [comment]
MQTT-Spy v1.0.1 beta 18  works fine with my Java10 installation
`java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)`

**Comment by TotallyInformation** [comment]
Indeed, that does work. Thanks.
