### ISSUE TITLE
Universal Messaging broker (Software AG) doesn't support underscores in ClientID

### ISSUE THREAD

**Issue by matgnt** [eclipse/paho.mqtt-spy#7]
According to the specification (MQTT 3.1.1) the ClientID allows only the following characters:
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

mqtt spy (0.5.3) generates a default ClientID that contains a "_" (underscore).
It generates it in the form of: <user>_<number>

This seems to be against the specification and stops you from connecting to e.g. "Universal Messaging" broker (from Software AG).

http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html
3.1.3.1 Client Identifier

**Comment by kamilfb** [comment]
Hi @matgnt,

The MQTT spec says: 
"The ClientId MUST be a UTF-8 encoded string as defined in Section 1.5.3 [MQTT-3.1.3-4]."

To me, this means any UTF-8 encoded string 0 to 65535 bytes.

The restriction you quote refers to server implementations, which might chose not to allow certain characters or lengths.

So the issue I think is: "Universal Messaging" broker from Software AG doesn't support underscores (and possibly other stuff too) in client IDs.

**Comment by matgnt** [comment]
Oh, this is how to read it? The encoded bytes is what they talk about...
I only wonder why the ClientId is the only place where they explicitly list the characters in addition to referring to the UTF8 section?! Because what would be the difference to e.g. a topic then?

And yes, this describes the server, but if it wasn't a MUST to support _ (and that is what I understood), the client's default should not use this as a default setting.

But you're right, only thing I can say is, that it doesn't work with the UM version I've tried.

Thanks @kamilfb !
Matthias

**Comment by kamilfb** [comment]
Hi @matgnt, I'll see what we can do about that - you're right, it'd be better to avoid the _ altogether if it's not necessary.

**Comment by kamilfb** [comment]
@matgnt , could you try the latest beta and see if it's any better?

**Comment by matgnt** [comment]
@kamilfb I tested it with 0.6.0 beta (build 56). Looks good! No _ (underscore) in the client id by default. I could connect to UM without any problems. Great!

**Comment by kamilfb** [comment]
Cool! Thank you for the feedback @matgnt
