### ISSUE TITLE
Annoying pop up

### ISSUE THREAD

**Issue by consolacion** [eclipse/paho.mqtt-spy#82]
How do I get rid of the annoying pop up asking for support?
It wont move, and will be on top of every application I open

Edit:
Seemed to have resolved itself

**Comment by evandal** [comment]
It happens to me regularly. Seems to be based on some random event. It pops up from time to time. Blocks the centre of the screen for all open apps, not just MQTT-Spy.  If I restart within a few minutes, it's still there. Try again 15 minutes later and sometimes it's gone. No way to get rid of it. It really needs to have a way to dismiss this pop-up. I do support the project and I still get nagged.
![image](https://github.com/eclipse/paho.mqtt-spy/assets/62754961/5ae09d13-d723-4a0d-bc5e-372409ec91a7)
![image](https://github.com/eclipse/paho.mqtt-spy/assets/62754961/3c854513-197d-48ad-a14d-dc2cd98564e9)

**Comment by wagfeliz** [comment]
Its happening with me, and I guess with all random peaple. If you put an invalid proxy it stops, but gives other problems.
Please fix it, its impossible to use this with this bug.
